name: schedule_calendar
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.3

  flutter_dotenv: ^5.1.0

  flutter_svg: ^2.0.9

  get_it: ^7.6.6

  http: ^1.1.2

  intl: ^0.18.1

  shimmer: ^3.0.0

  super_tooltip: ^2.0.7

  swipeable_button_view: ^0.0.2

  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: LemonMilkPro
      fonts:
        - asset: assets/fonts/Lemon-Milk-Pro-Ultra-Light.otf
        - asset: assets/fonts/Lemon-Milk-Pro-Regular.otf
        - asset: assets/fonts/Lemon-Milk-Pro-Medium.otf
        - asset: assets/fonts/Lemon-Milk-Pro-Bold.otf
